### PR TITLE
Unit tests

### PR DESCRIPTION
**Pull request by Sjlver**
This PR adds some tests (one, actually :) ) to the app. I thought this would be a good idea; it makes refactorings much less painful afterwards.

I wrote a little proxy for `chrome.hid`, which can simulate the messages sent by the OnlyKey. This enables testing of the app without a real key (and without the need for a user to press buttons on the key).

The test already uncovered a ~bug~ interesting feature of the app: it will always send an enter key after the password, because the "nextKey3" field is preselected and can't be deselected by the user. Is this intended?

BTW, what is the license of this code? We should add one. I'd suggest a two-clause BSD, unless you have other preferences.

### CODE REVIEW

**Comment by onlykey** [comment]
@Sjlver Nice, so I tried to replicate what you are saying where the Nextkey3 can't be deselected. I was not able to see this. For example, set a slot like this
image
And I see that just the password is typed, no return afterwards. Are you sure you didn't leave the Return after Google Auth OTP checked? If you have no Google Auth set that would result in a Return after the password.

**Comment by onlykey** [comment]
@Sjlver I think the simulation is a great idea. I am sure @rodgolpe will like this, no more creating custom OnlyKey firmware just to try something new! Rodney I think these changes look good can you check them over and see if we can merge?

**Comment by rodgolpe** [comment]
Good stuff, Jonas!

**Comment by Sjlver** [comment]
Cool, thanks for merging!

**Pull request merged**
